version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gemini_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'   
      - '15672:15672' 
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:

networks:
  app-network:
    driver: bridge 